export const getGOVTypes = () => {
  return {
    124: ['Abtei', 'Kirche'],
    76: ['Adeliges Gut', '(politische) Verwaltung'],
    193: ['Alm', 'Wohnplatz'],
    57: ['Amt (dänisches)', '(politische) Verwaltung'],
    78: ['Amt (kreisähnlich)', '(politische) Verwaltung'],
    1: ['Amt (Verwaltung)', '(politische) Verwaltung'],
    2: ['Amtsbezirk', '(politische) Verwaltung'],
    3: ['Amtsgericht', 'Gericht'],
    202: ['Amtsgerichtsbezirk', 'Gericht'],
    99: ['Amtshauptmannschaft', '(politische) Verwaltung'],
    250: ['Apostolische Administratur', 'Kirche'],
    134: ['arrondissement', '(politische) Verwaltung'],
    251: ['autonome Gemeinschaft', '(politische) Verwaltung'],
    118: ['Bahnhof', 'Verkehrswesen'],
    190: ['Ballei', '(politische) Verwaltung'],
    4: ['Bauerschaft', '(politische) Verwaltung'],
    192: ['Besatzungszone', '(politische) Verwaltung'],
    5: ['Bezirk', '(politische) Verwaltung'],
    110: ['Bezirksamt', '(politische) Verwaltung'],
    146: ['Bezirkshauptmannschaft', '(politische) Verwaltung'],
    6: ['Bistum', 'Kirche'],
    91: ['Bistumsregion', 'Kirche'],
    234: ['Borough', '(politische) Verwaltung'],
    7: ['Bundesland', '(politische) Verwaltung'],
    130: ['Bundesstaat', '(politische) Verwaltung'],
    8: ['Burg', 'Wohnplatz'],
    97: ['Bürgermeisterei', '(politische) Verwaltung'],
    135: ['canton', '(politische) Verwaltung'],
    159: ['Chutor', 'Wohnplatz'],
    136: ['commune', '(politische) Verwaltung'],
    9: ['Dekanat', 'Kirche'],
    260: ['Delegaturbezirk', 'Kirche'],
    10: ['Departement', '(politische) Verwaltung'],
    217: ['Direktionsbezirk', '(politische) Verwaltung'],
    170: ['Distrikt', '(politische) Verwaltung'],
    194: ['Distrikts-Amt', '(politische) Verwaltung'],
    11: ['Diözese', 'Kirche'],
    203: ['Domanialamt', '(politische) Verwaltung'],
    82: ['Domkapitel (Herrschaft)', '(politische) Verwaltung'],
    12: ['Dompfarrei', 'Kirche'],
    55: ['Dorf', 'Wohnplatz'],
    205: ['Dorfrat', '(politische) Verwaltung'],
    140: ['Einheitsgemeinde', '(politische) Verwaltung'],
    139: ['Einschicht', 'Wohnplatz'],
    67: ['Einöde', 'Wohnplatz'],
    148: ['Erfüllende Gemeinde', '(politische) Verwaltung'],
    249: ['Erzbischöfliches Amt', 'Kirche'],
    96: ['Erzbistum', 'Kirche'],
    182: ['Erzstift', '(politische) Verwaltung'],
    219: ['Expositur', 'Kirche'],
    13: ['Filiale', 'Kirche'],
    14: ['Flecken (Gebietskörperschaft)', '(politische) Verwaltung'],
    233: ['Flecken (Siedlung)', 'Wohnplatz'],
    15: ['Flurname', 'Platz'],
    109: ['Forstgutsbezirk', '(politische) Verwaltung'],
    102: ['Forsthaus', 'Wohnplatz'],
    16: ['Freistaat', '(politische) Verwaltung'],
    89: ['Friedhof', 'Platz'],
    221: ['Fylke', '(politische) Verwaltung'],
    115: ['Försterei', '(politische) Verwaltung'],
    60: ['Fürstentum', '(politische) Verwaltung'],
    17: ['Gebäude', 'Wohnplatz'],
    18: ['Gemeinde', '(politische) Verwaltung'],
    44: ['Pfarrverband', 'Kirche'],
    169: ['Gemeinde (schwedisch)', '(politische) Verwaltung'],
    156: ['Gemeindebezirk', '(politische) Verwaltung'],
    158: ['Gemeindeteil', '(politische) Verwaltung'],
    174: ['Generalbezirk', '(politische) Verwaltung'],
    228: ['Gerichtsamt', 'Gericht'],
    19: ['Gerichtsbezirk', 'Gericht'],
    112: ['Gespanschaft', '(politische) Verwaltung'],
    165: ['Gnotschaft', '(politische) Verwaltung'],
    157: ['Gouvernement', '(politische) Verwaltung'],
    20: ['Grafschaft', '(politische) Verwaltung'],
    246: ['Gromada', '(politische) Verwaltung'],
    61: ['Großherzogtum', '(politische) Verwaltung'],
    189: ['Großpriorat', '(politische) Verwaltung'],
    21: ['Gut (Gebäude)', 'Wohnplatz'],
    108: ['Gutsbezirk', '(politische) Verwaltung'],
    75: ['Güterdistrikt', '(politische) Verwaltung'],
    119: ['Haltestelle', 'Verkehrswesen'],
    83: ['Hansestadt', '(politische) Verwaltung'],
    79: ['Harde', 'Gericht'],
    68: ['Hauptort', 'Wohnplatz'],
    22: ['Herrschaft', '(politische) Verwaltung'],
    23: ['Herzogtum', '(politische) Verwaltung'],
    183: ['Hochstift', '(politische) Verwaltung'],
    24: ['Hof', 'Wohnplatz'],
    261: ['Hofschaft', 'Wohnplatz'],
    154: ['Honschaft', 'Gericht'],
    236: ['Häuser', 'Wohnplatz'],
    229: ['Häusergruppe', 'Wohnplatz'],
    231: ['Höfe', 'Wohnplatz'],
    107: ['Insel', 'geographische Typen'],
    88: ['Judet', '(politische) Verwaltung'],
    214: ['Kaiserreich', '(politische) Verwaltung'],
    184: ['Kammerschreiberei', '(politische) Verwaltung'],
    25: ['Kanton', '(politische) Verwaltung'],
    245: ['Kapelle', 'Kirche'],
    242: ['Katasteramt', 'Zivilverwaltung'],
    172: ['Katastralgemeinde', 'Zivilverwaltung'],
    66: ['Kirchdorf', 'Wohnplatz'],
    26: ['Kirche', 'Kirche'],
    210: ['Kirchenbund', 'Kirche'],
    92: ['Kirchengemeinde', 'Kirche'],
    27: ['Kirchenkreis', 'Kirche'],
    28: ['Kirchenprovinz', 'Kirche'],
    29: ['Kirchspiel', 'Kirche'],
    227: ['Kirchspielslandgemeinde', '(politische) Verwaltung'],
    84: ['Kirchspielvogtei', '(politische) Verwaltung'],
    81: ['Kloster (Gebiet)', '(politische) Verwaltung'],
    30: ['Kloster (Gebäude)', 'Kirche'],
    185: ['Klosteramt', '(politische) Verwaltung'],
    121: ['Kolonie', 'Wohnplatz'],
    113: ['Komitat', '(politische) Verwaltung'],
    191: ['Kommende', '(politische) Verwaltung'],
    153: ['Kommissariat', 'Kirche'],
    143: ['kommune', '(politische) Verwaltung'],
    32: ['Kreis', '(politische) Verwaltung'],
    222: ['Kreis (mittlere Verwaltungsebene)', '(politische) Verwaltung'],
    101: ['Kreisdirektion', '(politische) Verwaltung'],
    95: ['Kreisfreie Stadt', '(politische) Verwaltung'],
    175: ['Kreisgebiet', '(politische) Verwaltung'],
    100: ['Kreishauptmannschaft', '(politische) Verwaltung'],
    33: ['Kurfürstentum', '(politische) Verwaltung'],
    31: ['Königreich', '(politische) Verwaltung'],
    34: ['Land', '(politische) Verwaltung'],
    152: ['Landbürgermeisterei', '(politische) Verwaltung'],
    73: ['Landdrostei', '(politische) Verwaltung'],
    256: ['Landesbezirk', '(politische) Verwaltung'],
    35: ['Landeskirche', 'Kirche'],
    201: ['Landeskommissarbezirk', '(politische) Verwaltung'],
    216: ['Landesteil', '(politische) Verwaltung'],
    211: ['Landgebiet', '(politische) Verwaltung'],
    85: ['Landgemeinde', '(politische) Verwaltung'],
    257: ['Landgemeinde PL', '(politische) Verwaltung'],
    105: ['Landgericht', 'Gericht'],
    223: ['Landgericht (älterer Ordnung)', 'Gericht'],
    128: ['Landgrafschaft', '(politische) Verwaltung'],
    212: ['Landherrenschaft', '(politische) Verwaltung'],
    36: ['Landkreis', '(politische) Verwaltung'],
    149: ['Landratsamt', '(politische) Verwaltung'],
    266: ['Landratsbezirk', '(politische) Verwaltung'],
    47: ['Landschaft (Region)', 'geographische Typen'],
    80: ['Landschaft (Verwaltung)', '(politische) Verwaltung'],
    259: ['Landvogteibezirk', '(politische) Verwaltung'],
    252: ['local government', '(politische) Verwaltung'],
    264: ['Mairie', '(politische) Verwaltung'],
    167: ['Mandatsgebiet', '(politische) Verwaltung'],
    62: ['Markgrafschaft', '(politische) Verwaltung'],
    145: ['Markt', '(politische) Verwaltung'],
    180: ['Marktgemeinde', '(politische) Verwaltung'],
    87: ['Mühle', 'Wohnplatz'],
    244: ['Nebenkirche', 'Kirche'],
    37: ['Oberamt', '(politische) Verwaltung'],
    207: ['Oberamtsbezirk', '(politische) Verwaltung'],
    116: ['Oberförsterei', '(politische) Verwaltung'],
    151: ['Oberlandesgericht', 'Gericht'],
    138: ['Oberlandratsbezirk', '(politische) Verwaltung'],
    38: ['Oblast', '(politische) Verwaltung'],
    226: ['Obmannschaft', '(politische) Verwaltung'],
    254: ['Okrug', '(politische) Verwaltung'],
    39: ['Ort', 'Wohnplatz'],
    164: ['Ortsbezirk', '(politische) Verwaltung'],
    144: ['Ortschaft', '(politische) Verwaltung'],
    163: ['Ortsgemeinde', '(politische) Verwaltung'],
    40: ['Ortsteil', 'Wohnplatz'],
    247: ['Ortsteil (Verwaltung)', '(politische) Verwaltung'],
    41: ['Pfarr-Rektorat', 'Kirche'],
    65: ['Pfarrdorf', 'Wohnplatz'],
    42: ['Pfarrei', 'Kirche'],
    43: ['Pfarrkuratie', 'Kirche'],
    224: ['Pfleggericht', 'Gericht'],
    243: ['Propstei', 'Kirche'],
    176: ['Protektorat', '(politische) Verwaltung'],
    45: ['Provinz', '(politische) Verwaltung'],
    168: ['Provinz (schwedisch)', '(politische) Verwaltung'],
    232: ['Randort', 'Wohnplatz'],
    63: ['Rayon', '(politische) Verwaltung'],
    46: ['Regierungsbezirk', '(politische) Verwaltung'],
    133: ['Region (französisch)', '(politische) Verwaltung'],
    137: ['Region (Gebietskörperschaft)', '(politische) Verwaltung'],
    155: ['Region (katholische Kirche)', 'Kirche'],
    206: ['Regionalkirchenamt', 'Kirche'],
    125: ['Reichsabtei', '(politische) Verwaltung'],
    142: ['Reichsgau', '(politische) Verwaltung'],
    215: ['Reichshälfte', '(politische) Verwaltung'],
    173: ['Reichskommissariat', '(politische) Verwaltung'],
    77: ['Reichskreis', '(politische) Verwaltung'],
    177: ['Reichsritterschaft', '(politische) Verwaltung'],
    93: ['Reichsstadt', '(politische) Verwaltung'],
    253: ['Religionsgemeinschaft', 'Kirche'],
    225: ['Rentamt (älterer Ordnung)', '(politische) Verwaltung'],
    186: ['Rentkammer', '(politische) Verwaltung'],
    56: ['Republik', '(politische) Verwaltung'],
    178: ['Ritterkanton', '(politische) Verwaltung'],
    179: ['Ritterkreis', '(politische) Verwaltung'],
    188: ['Ritterorden', '(politische) Verwaltung'],
    204: ['Ritterschaftliches Amt', '(politische) Verwaltung'],
    181: ['Rotte', 'Wohnplatz'],
    166: ['Ruine', 'Platz'],
    48: ['Samtgemeinde', '(politische) Verwaltung'],
    111: ['Schloss', 'Wohnplatz'],
    248: ['Schulzenamt', '(politische) Verwaltung'],
    120: ['Siedlung', 'Wohnplatz'],
    238: ['Siedlung städtischen Typs', 'Wohnplatz'],
    237: ['Siedlungsrat', '(politische) Verwaltung'],
    267: ['sognekommune', '(politische) Verwaltung'],
    160: ['Sowjetrepublik', '(politische) Verwaltung'],
    49: ['Sprengel', 'Kirche'],
    263: ['Sprengel (obere Verwaltung)', 'Kirche'],
    50: ['Staat', '(politische) Verwaltung'],
    71: ['Staatenbund', '(politische) Verwaltung'],
    218: ['Stadt (Einheitsgemeinde)', '(politische) Verwaltung'],
    150: ['Stadt (Gebietskörperschaft)', '(politische) Verwaltung'],
    51: ['Stadt (Siedlung)', 'Wohnplatz'],
    162: ['Stadt- und Landgemeinde', '(politische) Verwaltung'],
    52: ['Stadtbezirk', '(politische) Verwaltung'],
    258: ['Stadtgemeinde (PL)', '(politische) Verwaltung'],
    255: ['Stadtgut', '(politische) Verwaltung'],
    171: ['Stadthauptmannschaft', '(politische) Verwaltung'],
    53: ['Stadtkreis', '(politische) Verwaltung'],
    213: ['Stadtrat', '(politische) Verwaltung'],
    54: ['Stadtteil', 'Wohnplatz'],
    262: ['Stadtteil (Verwaltung)', '(politische) Verwaltung'],
    103: ['Standesamt', 'Zivilverwaltung'],
    230: ['Streusiedlung', 'Wohnplatz'],
    265: ['Sultanat', '(politische) Verwaltung'],
    126: ['Syssel', '(politische) Verwaltung'],
    86: ['Teilprovinz', '(politische) Verwaltung'],
    240: ['Ujesd', '(politische) Verwaltung'],
    58: ['Unionsrepublik', '(politische) Verwaltung'],
    235: ['Unitary Authority', '(politische) Verwaltung'],
    117: ['Unterförsterei', '(politische) Verwaltung'],
    98: ['veraltet (Amtsgericht Gebäude)', 'Sonstige'],
    195: ['veraltet (Bundessozialgericht)', 'Sonstige'],
    198: ['veraltet (früher: Bundesverwaltungsgericht)', 'Sonstige'],
    199: ['veraltet (früher: Landesverwaltungsgericht)', 'Sonstige'],
    200: ['veraltet (früher: Verwaltungsgericht)', 'Sonstige'],
    74: ['veraltet (Gut)', 'Sonstige'],
    196: ['veraltet (Landessozialgericht)', 'Sonstige'],
    147: ['veraltet (Politischer Bezirk)', 'Sonstige'],
    197: ['veraltet (Sozialgericht)', 'Sonstige'],
    104: ['veraltet (Standesamt (Gebäude))', 'Sonstige'],
    122: ['Verbandsgemeinde', '(politische) Verwaltung'],
    239: ['Verwaltungsamt', '(politische) Verwaltung'],
    161: ['Verwaltungsbezirk', '(politische) Verwaltung'],
    94: ['Verwaltungsgemeinschaft', '(politische) Verwaltung'],
    127: ['Verwaltungsverband', '(politische) Verwaltung'],
    114: ['Vest', 'Gericht'],
    70: ['Vogtei', 'Gericht'],
    72: ['Volksrepublik', '(politische) Verwaltung'],
    64: ['Vorwerk', 'Wohnplatz'],
    131: ['Weichbild', '(politische) Verwaltung'],
    69: ['Weiler', 'Wohnplatz'],
    129: ['Wohnplatz', 'Wohnplatz'],
    59: ['Wojewodschaft', '(politische) Verwaltung'],
    241: ['Wolost', '(politische) Verwaltung'],
    90: ['Wüstung', 'Platz'],
    187: ['zu überprüfen', 'Sonstige'],
  };
};
