import { normalizeGeonames } from './normalizeGeonames';

it('the entries of Geonames were correctly pre-processed', () => {
  const inputValue = [
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      bbox: {
        east: 18.800645169287666,
        south: 54.26415059853274,
        north: 54.44038940146726,
        west: 18.497594830712334,
        accuracyLevel: 2,
      },
      asciiName: 'Gdansk',
      astergdem: 19,
      countryId: '798544',
      fcl: 'P',
      srtm3: -32768,
      score: 201.72769165039062,
      adminId2: '7531002',
      adminId3: '7531890',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.35227',
      fcode: 'PPLA',
      continentCode: 'EU',
      adminCode2: '2261',
      adminCode3: '226101',
      adminCode1: '82',
      lng: '18.64912',
      geonameId: 3099434,
      toponymName: 'Gdańsk',
      population: 461865,
      adminName5: '',
      adminName4: '',
      adminName3: 'Gdańsk',
      alternateNames: [
        { name: 'Gdansk', lang: 'af' },
        { name: 'Dantsic', lang: 'ang' },
        { name: 'غدانسك', lang: 'ar' },
        { name: 'Gdansk', lang: 'ast' },
        { name: 'Qdansk', lang: 'az' },
        { name: 'Гданьск', lang: 'be' },
        { name: 'Гданск', lang: 'bg' },
        { name: 'Gdansk', lang: 'ca' },
        { name: 'Гданьск', lang: 'ce' },
        { name: 'گدانسک', lang: 'ckb' },
        { name: 'Gdansk', lang: 'co' },
        { name: 'Gdansk', lang: 'crh' },
        { name: 'Gdaňsk', lang: 'cs' },
        { name: 'Gduńsk', lang: 'csb' },
        { name: 'Гъданьскъ', lang: 'cu' },
        { name: 'Гданьск', lang: 'cv' },
        { isPreferredName: true, name: 'Gdańsk', lang: 'cy' },
        { name: 'Gdańsk', lang: 'da' },
        { name: 'Danzig', lang: 'de' },
        { name: 'Γκντανσκ', lang: 'el' },
        { isPreferredName: true, name: 'Gdansk', lang: 'en' },
        { name: 'Gdańsk', lang: 'eo' },
        { isPreferredName: true, name: 'Gdansk', lang: 'es' },
        { name: 'Gdańsk', lang: 'et' },
        { name: 'Gdansk', lang: 'eu' },
        { name: 'Gdansk', lang: 'ext' },
        { name: 'گدانسک', lang: 'fa' },
        { name: 'Gdańsk', lang: 'fi' },
        { name: 'Gdansk', lang: 'fo' },
        { name: 'Gdańsk', lang: 'fr' },
        { name: 'Gdansk', lang: 'fy' },
        { name: 'Gdansk', lang: 'gl' },
        { name: 'גדנסק', lang: 'he' },
        { name: 'Gdanjsk', lang: 'hr' },
        { name: 'Gdańsk', lang: 'hu' },
        { name: 'Գդանսկ', lang: 'hy' },
        { name: 'GDN', lang: 'iata' },
        { name: 'Gdańsk', lang: 'id' },
        { name: 'Gdańsk', lang: 'is' },
        { name: 'Danzica', lang: 'it' },
        { name: 'グダニスク', lang: 'ja' },
        { name: 'გდანსკი', lang: 'ka' },
        { name: '그단스크', lang: 'ko' },
        { name: 'Gedanum', lang: 'la' },
        { name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk', lang: 'link' },
        { name: 'Danzica', lang: 'lmo' },
        { name: 'Gdanskas', lang: 'lt' },
        { name: 'Gdaņska', lang: 'lv' },
        { name: 'Гданьск', lang: 'mhr' },
        { name: 'Гдањск', lang: 'mk' },
        { name: 'गदान्स्क', lang: 'mr' },
        { name: 'Gdańsk', lang: 'na' },
        { name: 'Danzica', lang: 'nap' },
        { name: 'Danzig', lang: 'nds' },
        { name: 'Gdansk', lang: 'nl' },
        { name: 'Gdańsk', lang: 'no' },
        { name: 'Гданьск', lang: 'os' },
        { name: 'Gdańsk', lang: 'pl' },
        { name: 'گدانسک', lang: 'pnb' },
        { name: 'Gdańsk', lang: 'pt' },
        { name: 'Gdańsk', lang: 'ro' },
        { name: 'Гданьск', lang: 'ru' },
        { name: 'Dànzica', lang: 'scn' },
        { name: 'Gdansk', lang: 'sk' },
        { name: 'Gdansk', lang: 'sl' },
        { name: 'Гдањск', lang: 'sr' },
        { name: 'Gdańsk', lang: 'sv' },
        { name: 'கதான்ஸ்க்', lang: 'ta' },
        { name: 'กดัญสก์', lang: 'th' },
        { name: 'Gdansk', lang: 'tr' },
        { name: 'Гданськ', lang: 'uk' },
        { name: 'PLGDN', lang: 'unlc' },
        { name: 'Gdansk', lang: 'vep' },
        { name: 'გდანსკი', lang: 'xmf' },
        { name: 'דאנציג', lang: 'yi' },
        { name: 'Gdansk', lang: 'zea' },
        { name: '格但斯克', lang: 'zh' },
        { name: '格但斯克', lang: 'zh-CN' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdansk',
      fclName: 'city, village,...',
      countryName: 'Poland',
      fcodeName: 'seat of a first-order administrative division',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/3099434',
      matchings: [
        { db: 'gnd', id: '4011039-4', link: 'https://d-nb.info/gnd/4011039-4' },
        {
          db: 'gov',
          id: 'DANZIGJO94HI',
          link: 'https://gov.genealogy.net/item/show/DANZIGJO94HI',
        },
        { db: 'teryt_simc', id: '0933016' },
        { db: 'teryt_simc', id: '2261011' },
        { db: 'wikidata', id: '1792', link: 'https://www.wikidata.org/wiki/Q1792' },
      ],
    },
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      bbox: {
        east: 18.9503794132357,
        south: 54.2749744898979,
        north: 54.4472181554226,
        west: 18.429497094525,
        accuracyLevel: 10,
      },
      asciiName: 'Gdansk',
      astergdem: 4,
      countryId: '798544',
      fcl: 'A',
      srtm3: 1,
      score: 53.91399002075195,
      adminId2: '7531002',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.36112',
      fcode: 'ADM2',
      continentCode: 'EU',
      adminCode2: '2261',
      adminCode1: '82',
      lng: '18.68976',
      geonameId: 7531002,
      toponymName: 'Gdańsk',
      population: 464254,
      adminName5: '',
      adminName4: '',
      adminName3: '',
      alternateNames: [
        { name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk', lang: 'link' },
        { name: 'Powiat gdański', lang: 'pl' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdańsk',
      fclName: 'country, state, region,...',
      countryName: 'Poland',
      fcodeName: 'second-order administrative division',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/7531002',
      matchings: [
        {
          db: 'gov',
          id: 'object_218108',
          link: 'https://gov.genealogy.net/item/show/object_218108',
        },
        { db: 'wikidata', id: '49630826', link: 'https://www.wikidata.org/wiki/Q49630826' },
      ],
    },
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      asciiName: 'Gdansk Lech Walesa Airport',
      astergdem: 131,
      countryId: '798544',
      fcl: 'S',
      srtm3: 134,
      score: 47.6536865234375,
      adminId2: '7531002',
      adminId3: '7531890',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.37808',
      fcode: 'AIRP',
      continentCode: 'EU',
      elevation: 149,
      adminCode2: '2261',
      adminCode3: '226101',
      adminCode1: '82',
      lng: '18.46823',
      geonameId: 3099426,
      toponymName: 'Gdańsk Lech Wałęsa Airport',
      population: 0,
      adminName5: '',
      adminName4: '',
      adminName3: 'Gdańsk',
      alternateNames: [
        { name: 'Gdańsk Lech Wałęsa Airport', lang: 'en' },
        { name: 'Aéroport Lech Wałęsa de Gdańsk', lang: 'fr' },
        { name: 'GDN', lang: 'iata' },
        { name: 'EPGD', lang: 'icao' },
        {
          name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk_Lech_Wa%C5%82%C4%99sa_Airport',
          lang: 'link',
        },
        { name: 'Port Lotniczy Gdańsk im. Lecha Wałęsy', lang: 'pl' },
        { name: 'Гданьский аэропорт имени Леха Валенсы', lang: 'ru' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdańsk Lech Wałęsa Airport',
      fclName: 'spot, building, farm',
      countryName: 'Poland',
      fcodeName: 'airport',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/3099426',
      matchings: [{ db: 'wikidata', id: '779984', link: 'https://www.wikidata.org/wiki/Q779984' }],
    },
  ];
  const expectedValue = normalizeGeonames(inputValue);
  expect(expectedValue).toEqual([
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      bbox: {
        east: 18.800645169287666,
        south: 54.26415059853274,
        north: 54.44038940146726,
        west: 18.497594830712334,
        accuracyLevel: 2,
      },
      asciiName: 'Gdansk',
      astergdem: 19,
      countryId: '798544',
      fcl: 'P',
      srtm3: -32768,
      score: 201.72769165039062,
      adminId2: '7531002',
      adminId3: '7531890',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.35227',
      fcode: 'PPLA',
      continentCode: 'EU',
      adminCode2: '2261',
      adminCode3: '226101',
      adminCode1: '82',
      lng: '18.64912',
      id: '3099434',
      toponymName: 'Gdańsk',
      population: 461865,
      adminName5: '',
      adminName4: '',
      adminName3: 'Gdańsk',
      alternateNames: [
        { name: 'Gdansk', lang: 'af' },
        { name: 'Dantsic', lang: 'ang' },
        { name: 'غدانسك', lang: 'ar' },
        { name: 'Gdansk', lang: 'ast' },
        { name: 'Qdansk', lang: 'az' },
        { name: 'Гданьск', lang: 'be' },
        { name: 'Гданск', lang: 'bg' },
        { name: 'Gdansk', lang: 'ca' },
        { name: 'Гданьск', lang: 'ce' },
        { name: 'گدانسک', lang: 'ckb' },
        { name: 'Gdansk', lang: 'co' },
        { name: 'Gdansk', lang: 'crh' },
        { name: 'Gdaňsk', lang: 'cs' },
        { name: 'Gduńsk', lang: 'csb' },
        { name: 'Гъданьскъ', lang: 'cu' },
        { name: 'Гданьск', lang: 'cv' },
        { isPreferredName: true, name: 'Gdańsk', lang: 'cy' },
        { name: 'Gdańsk', lang: 'da' },
        { name: 'Danzig', lang: 'de' },
        { name: 'Γκντανσκ', lang: 'el' },
        { isPreferredName: true, name: 'Gdansk', lang: 'en' },
        { name: 'Gdańsk', lang: 'eo' },
        { isPreferredName: true, name: 'Gdansk', lang: 'es' },
        { name: 'Gdańsk', lang: 'et' },
        { name: 'Gdansk', lang: 'eu' },
        { name: 'Gdansk', lang: 'ext' },
        { name: 'گدانسک', lang: 'fa' },
        { name: 'Gdańsk', lang: 'fi' },
        { name: 'Gdansk', lang: 'fo' },
        { name: 'Gdańsk', lang: 'fr' },
        { name: 'Gdansk', lang: 'fy' },
        { name: 'Gdansk', lang: 'gl' },
        { name: 'גדנסק', lang: 'he' },
        { name: 'Gdanjsk', lang: 'hr' },
        { name: 'Gdańsk', lang: 'hu' },
        { name: 'Գդանսկ', lang: 'hy' },
        { name: 'GDN', lang: 'iata' },
        { name: 'Gdańsk', lang: 'id' },
        { name: 'Gdańsk', lang: 'is' },
        { name: 'Danzica', lang: 'it' },
        { name: 'グダニスク', lang: 'ja' },
        { name: 'გდანსკი', lang: 'ka' },
        { name: '그단스크', lang: 'ko' },
        { name: 'Gedanum', lang: 'la' },
        { name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk', lang: 'link' },
        { name: 'Danzica', lang: 'lmo' },
        { name: 'Gdanskas', lang: 'lt' },
        { name: 'Gdaņska', lang: 'lv' },
        { name: 'Гданьск', lang: 'mhr' },
        { name: 'Гдањск', lang: 'mk' },
        { name: 'गदान्स्क', lang: 'mr' },
        { name: 'Gdańsk', lang: 'na' },
        { name: 'Danzica', lang: 'nap' },
        { name: 'Danzig', lang: 'nds' },
        { name: 'Gdansk', lang: 'nl' },
        { name: 'Gdańsk', lang: 'no' },
        { name: 'Гданьск', lang: 'os' },
        { name: 'Gdańsk', lang: 'pl' },
        { name: 'گدانسک', lang: 'pnb' },
        { name: 'Gdańsk', lang: 'pt' },
        { name: 'Gdańsk', lang: 'ro' },
        { name: 'Гданьск', lang: 'ru' },
        { name: 'Dànzica', lang: 'scn' },
        { name: 'Gdansk', lang: 'sk' },
        { name: 'Gdansk', lang: 'sl' },
        { name: 'Гдањск', lang: 'sr' },
        { name: 'Gdańsk', lang: 'sv' },
        { name: 'கதான்ஸ்க்', lang: 'ta' },
        { name: 'กดัญสก์', lang: 'th' },
        { name: 'Gdansk', lang: 'tr' },
        { name: 'Гданськ', lang: 'uk' },
        { name: 'PLGDN', lang: 'unlc' },
        { name: 'Gdansk', lang: 'vep' },
        { name: 'გდანსკი', lang: 'xmf' },
        { name: 'דאנציג', lang: 'yi' },
        { name: 'Gdansk', lang: 'zea' },
        { name: '格但斯克', lang: 'zh' },
        { name: '格但斯克', lang: 'zh-CN' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdansk',
      type: 'city, village,...',
      countryName: 'Poland',
      fcodeName: 'seat of a first-order administrative division',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/3099434',
      matchings: [
        { db: 'gnd', id: '4011039-4', link: 'https://d-nb.info/gnd/4011039-4' },
        {
          db: 'gov',
          id: 'DANZIGJO94HI',
          link: 'https://gov.genealogy.net/item/show/DANZIGJO94HI',
        },
        { db: 'teryt_simc', id: '0933016' },
        { db: 'teryt_simc', id: '2261011' },
        { db: 'wikidata', id: '1792', link: 'https://www.wikidata.org/wiki/Q1792' },
      ],
    },
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      bbox: {
        east: 18.9503794132357,
        south: 54.2749744898979,
        north: 54.4472181554226,
        west: 18.429497094525,
        accuracyLevel: 10,
      },
      asciiName: 'Gdansk',
      astergdem: 4,
      countryId: '798544',
      fcl: 'A',
      srtm3: 1,
      score: 53.91399002075195,
      adminId2: '7531002',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.36112',
      fcode: 'ADM2',
      continentCode: 'EU',
      adminCode2: '2261',
      adminCode1: '82',
      lng: '18.68976',
      id: '7531002',
      toponymName: 'Gdańsk',
      population: 464254,
      adminName5: '',
      adminName4: '',
      adminName3: '',
      alternateNames: [
        { name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk', lang: 'link' },
        { name: 'Powiat gdański', lang: 'pl' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdańsk',
      type: 'country, state, region,...',
      countryName: 'Poland',
      fcodeName: 'second-order administrative division',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/7531002',
      matchings: [
        {
          db: 'gov',
          id: 'object_218108',
          link: 'https://gov.genealogy.net/item/show/object_218108',
        },
        { db: 'wikidata', id: '49630826', link: 'https://www.wikidata.org/wiki/Q49630826' },
      ],
    },
    {
      timezone: { gmtOffset: 1, timeZoneId: 'Europe/Warsaw', dstOffset: 2 },
      asciiName: 'Gdansk Lech Walesa Airport',
      astergdem: 131,
      countryId: '798544',
      fcl: 'S',
      srtm3: 134,
      score: 47.6536865234375,
      adminId2: '7531002',
      adminId3: '7531890',
      countryCode: 'PL',
      adminCodes1: { ISO3166_2: '22' },
      adminId1: '3337496',
      lat: '54.37808',
      fcode: 'AIRP',
      continentCode: 'EU',
      elevation: 149,
      adminCode2: '2261',
      adminCode3: '226101',
      adminCode1: '82',
      lng: '18.46823',
      id: '3099426',
      toponymName: 'Gdańsk Lech Wałęsa Airport',
      population: 0,
      adminName5: '',
      adminName4: '',
      adminName3: 'Gdańsk',
      alternateNames: [
        { name: 'Gdańsk Lech Wałęsa Airport', lang: 'en' },
        { name: 'Aéroport Lech Wałęsa de Gdańsk', lang: 'fr' },
        { name: 'GDN', lang: 'iata' },
        { name: 'EPGD', lang: 'icao' },
        {
          name: 'https://en.wikipedia.org/wiki/Gda%C5%84sk_Lech_Wa%C5%82%C4%99sa_Airport',
          lang: 'link',
        },
        { name: 'Port Lotniczy Gdańsk im. Lecha Wałęsy', lang: 'pl' },
        { name: 'Гданьский аэропорт имени Леха Валенсы', lang: 'ru' },
      ],
      adminName2: 'Gdańsk',
      name: 'Gdańsk Lech Wałęsa Airport',
      type: 'spot, building, farm',
      countryName: 'Poland',
      fcodeName: 'airport',
      adminName1: 'Pomerania',
      link: 'https://www.geonames.org/3099426',
      matchings: [{ db: 'wikidata', id: '779984', link: 'https://www.wikidata.org/wiki/Q779984' }],
    },
  ]);
});
